### ISSUE TITLE
Do we need bem-core in deps if we have bem-components?

### ISSUE THREAD

**Issue by zxqfox** [bem/generator-bem-stub#101]
Just because bem-components knows more about the needed version of bem-core.

**Comment by tadatuta** [comment]
We don't. And, BTW, it's high time to update bem-components version ;)

**Comment by eGavr** [comment]
@tadatuta , yes,  we don't.BUT! Did you remember the problem with broken `bem-core@2.4.0`,  and `bem-components` installed it,  but we need not broken `bem-core@2.3.0`.
Because of this situation, I've decided to specify `bem-core` even if `bem-components` has been chosen.

After generation of the project, I think, that it is not so difficult to remove one line from `bower.json` ;)

**Comment by zxqfox** [comment]
@eGavr Yup. But why you forcing me to make these changes if the reason I using generator is automatization? ;-)

**Comment by eGavr** [comment]
Will be done ;)
